### ISSUE TITLE
Add an unfinished button in HTML

### ISSUE THREAD

**Issue by MatthewMeacham** [MatthewMeacham/HomeworkOrganizer#15] opened 2015-07-19 00:10 UTC
Add an unfinished button in the box of the finished assignments

**Comment by hwaldstein** [comment] 2015-07-21 22:04
Duplicate of #12

**Comment by MatthewMeacham** [comment] 2015-07-22 00:32
Not a duplicate of #12, this was for Garrison, #12 is for Eddie to create the code.

**Closed as completed** 2015-07-24 02:16 UTC
Labels: enhancement
